name: gm
description: Fast linear algebra library for Dart.
version: 0.0.2
repository: https://github.com/dartgfx/gm

environment:
  sdk: ^3.3.0

dev_dependencies:
  benchmark_harness: ^2.3.0
  vector_math: ^2.1.4
